inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Exclude:
    - src/alexa_processor.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*

Metrics/PerceivedComplexity:
  Exclude:
    - spec/**/*

Naming/MethodParameterName:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/**/*

Style/FormatStringToken:
  Enabled: false
