name: unit tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: "3.1"
        bundler-cache: true
    - run:
    - name: rubocop
      run: |
        bundle install
        bundle exec rubocop
    - name: Build and test with rspec
      env:
        APP_NAME: snomer
        LOGO_URL: https://www.stpaul.gov/
        RAILS_ENV: test
    - run: |
        bundle install
        bundle exec rake
