name: unit tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: rubocop
      run: |
        bundle install
        bundle exec rubocop
    - name: Build and test with rspec
      env:
        APP_NAME: snomer
        LOGO_URL: https://www.stpaul.gov/
        RAILS_ENV: test
      run: bundle exec rake
